config/routes.rb
Rails.application.routes.draw do
  root to: 'villas#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :villas do 
    collection do
      get 'search'
    end
  end

  resources :reservations


  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :villa
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reservations
end

app/models/villa.rb
class Villa < ApplicationRecord
  has_many :reservations

    def new
      @villa = Villa.new
    end
  
    end

app/models/villa_search.rb
class VillaSearch
    attr_reader :date_start, :date_end

    def initialize(params)
        params ||= {}

        @date_start = params[:date_start]
        @date_end = params[:date_end]
    end

    def scope
        Villa.where.not(id: Reservation.select('villa_id').where('date(end_date) >= ? AND date(start_date) <= ?', date_start, date_end))
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        villas_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

end

app/controllers/reservations_controller.rb
require 'date'

class ReservationsController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end

    def isDiscountable(start_date, end_date)
        if (start_date.to_date.wday >= 1 and start_date.to_date.wday < 5) and end_date.to_date.wday < 5
            true
        else
            false
        end
    end
        
    def show
        @reservation = Reservation.find(params[:id])
    end

    def new
        @reservation = Reservation.new
        @start_date = params[:start_date]
        @end_date = params[:end_date]
        @price = params[:price].to_i
        session[:villa_id] = params[:villa_id]
        session[:price] = params[:price]
        
        if isDiscountable(@start_date, @end_date)
            @price *= 0.90 
        end
        session[:price] = @price
    end
        
    
    def create
        @reservation = Reservation.new(reservation_params)
        @reservation.user_id = current_user.id
        @reservation.villa_id = session[:villa_id]
        @reservation.price = session[:price]
        @villa = Villa.find(session[:villa_id])
        @reservation.save
         
        if @reservation.save
            @user = current_user.email
            ReservationMailer.reservation(@reservation, @user, @villa).deliver
            flash[:success] = "Réservation effectuée avec succès, vous recevrez un mail de confirmation dans quelques instants."
            redirect_to reservations_path
        end

    end

    private
    def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :nbAdults, :nbChilds, :price, :description)
    end

end

app/controllers/villas_controller.rb
class VillasController < ApplicationController

    def index
        @search = VillaSearch.new(params[:search])
        @villas = @search.scope
    end

    def show
        @villa = Villa.find(params[:id])
    end
    
    def new
        @villa = Villa.new
    end
    
    
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand" style="font-size: 1.5rem">Booking</a>
  
    <% if current_user %>
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'My reservations', reservations_path %></li>
                <div class="dropdown-divider"></div>
                  <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                </div>
            </div>
        </div>
        
    <% else %>
    <div class="d-flex align-items-center">    
        <button class="btn btn-light mr-3"><%= link_to 'Sign up', new_user_registration_path %></button>
        <button class="btn btn-light mr-3"><%= link_to 'Login', new_user_session_path %></button>
    </div>
    
    <% end %>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VillaBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/reservations/new.html.erb
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100%; min-height: 100vh;">
<div class="card w-50">
<div class="card-body d-flex justify-content-center">
<%= form_for @reservation do |t| %>
    Start: <%= t.text_field :start_date, value: @start_date %><br />
    End: <%= t.text_field :end_date, value: @end_date %><br />
    NbAdults: <%= t.number_field :nbAdults %><br />
    NbChilds: <%= t.number_field :nbChilds %><br />
    Nature du Séjour: <%= t.text_field :description %><br /> 

    <strong>Prix : <%= @price %></strong> euros
    <%= t.submit "Confirmer" %>
  <% end %>

  </div>
  </div>
  </div>

app/views/villas/index.html.erb
<div class="container mt-5 d-flex justify-content-center search">
    <div class="row">
        <%= form_tag villas_path, method: :get do %>
            <%= date_field_tag 'search[date_start]', @search.date_start, min: Date.today, value: @search.date_start || Date.today %>
            <%= date_field_tag 'search[date_end]', @search.date_end, value: @search.date_start || Date.today + 1 %>
            <%= submit_tag 'Search' %>
        <%end%>
    </div>
</div>

<div class="container mt-5 results d-flex justify-content-center flex-column ">
    <% @villas.each do |x| %>
        <div class="row justify-content-center">
            <%= link_to villa_path(:id => x.id) do %> 
            <div class="card result-card w-50" style="width: 18rem;">
                <%= image_tag x.img_url, alt: "villa", class:"card-img-top" %>
                <div class="card-body">
                    <h5 class="card-title"><%= x.id%></h5>
                    <p class="card-text"><%= x.city%></p>
                    <%= link_to 'Book !', new_reservation_path(:villa_id => x.id, :price => x.price, :start_date => @search.date_start, :end_date => @search.date_end) %>
                </div>
            </div>
        <% end %>
            </div>
    <% end%>
</div>

app/views/villas/show.html.erb
<%= image_tag @villa.img_url %>
<%= @villa.city %>
<%= @villa.country %>
<%= @villa.id %>